export const errorCodeIndex: { [key: string]: number } = {
    "INVALID_REQUEST": 400,
    "NOT_A_DISCORD_ID": 404,
    "INVALID_CODE_FOR_ACCESS_TOKEN_EXCHANGE": 401,
    "INVALID_REFRESH_TOKEN": 404,
    "INVALID_ACCESS_TOKEN": 404,
    "ALTERED_OAUTH2_STATE": 403,
    "EXPIRED_SESSION": 440,
    "UNAUTHORIZED": 401,
    "UNSUPPORTED_LANGUAGE": 400,
    "UNKNOWN_INTERNAL_USER": 404,
};